# Generated by Django 3.2.5 on 2022-04-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmitAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField(choices=[(1, 'オフィス'), (2, '自宅'), (3, 'コワーキングスペース'), (4, '出張先'), (5, 'その他')], default=None, verbose_name='勤務先')),
                ('in_out', models.IntegerField(choices=[(0, '出勤'), (1, '退勤'), (2, '休憩 始'), (2, '休憩 終')], default=None, verbose_name='出勤/退勤')),
                ('remarks', models.TextField(blank=True, max_length=300, null=True, verbose_name='備考欄')),
                ('time', models.TimeField(verbose_name='打刻時間')),
                ('date', models.DateField(verbose_name='打刻日')),
                ('employee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員名')),
            ],
            options={
                'db_table': 'attendance',
            },
        ),
    ]
